#ifndef _PARAMS_H_
#define _PARAMS_H_

const double BACKGROUND_FOREGROUND_THRESHOLD = 90.0;

const double FRAME_FIELD_REGULARIZER_WEIGHT = 0.1;
const double FRAME_FIELD_SMOOTHNESS_WEIGHT = 50.0;

const double PRUNE_SHORT_BRANCHES_RATIO = 0.75;

const int MAX_NUMBER_OF_WHITE_PIXELS_IN_A_CONTRACTIBLE_LOOP = 4;


#endif
